### ISSUE TITLE
Complication with compiling

### ISSUE THREAD

**Issue by st2092** [psxdev/ps4link#2]
I am having trouble compiling libdebugnet. I am getting errors in the following format: "unknown type name [type]; do you mean [type]?". Here is an error I get when compiling:  /usr/local/ps4dev/libps4/include/stdarg.h:39:9: error: unknown type name '__va_list'; did you mean 'va_list'? I am trying to compile on Mac OS X 10.11 with Xcode 7.2.

**Comment by psxdev** [comment]
Libdebugnet is ps4 code You need clang different than used in Xcode and use includes from libps4. If not you are using compiler for OS X code and it will fail.

**Comment by psxdev** [comment]
custom clang is needed in osx to compile ps4 code
